CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS industry VARCHAR(160) NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS countries JSONB NOT NULL DEFAULT '[]';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS cities JSONB NOT NULL DEFAULT '[]';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS company_size VARCHAR(80);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS keywords JSONB NOT NULL DEFAULT '[]';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS website_filters JSONB NOT NULL DEFAULT '[]';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS language VARCHAR(80) NOT NULL DEFAULT 'English';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS offer TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS cta VARCHAR(220) NOT NULL DEFAULT 'Book a quick call';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS email_tone VARCHAR(80) NOT NULL DEFAULT 'Professional';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS signature TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE leads ADD COLUMN IF NOT EXISTS campaign_id UUID REFERENCES campaigns(id) ON DELETE SET NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS industry VARCHAR(160);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS contact VARCHAR(160);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS revenue NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE email_messages ADD COLUMN IF NOT EXISTS preview VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE email_messages ADD COLUMN IF NOT EXISTS cta VARCHAR(220) NOT NULL DEFAULT '';
ALTER TABLE email_messages ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id VARCHAR(128) NOT NULL,
  kind VARCHAR(32) NOT NULL DEFAULT 'info',
  title VARCHAR(180) NOT NULL,
  message TEXT NOT NULL,
  read_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS workspace_profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id VARCHAR(128) UNIQUE NOT NULL,
  workspace VARCHAR(180) NOT NULL DEFAULT 'Outreach workspace',
  company VARCHAR(180) NOT NULL DEFAULT '',
  avatar_url VARCHAR(500),
  timezone VARCHAR(80) NOT NULL DEFAULT 'UTC',
  language VARCHAR(80) NOT NULL DEFAULT 'English',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id VARCHAR(128) UNIQUE NOT NULL,
  general JSONB NOT NULL DEFAULT '{}',
  ai JSONB NOT NULL DEFAULT '{}',
  email JSONB NOT NULL DEFAULT '{}',
  billing JSONB NOT NULL DEFAULT '{}',
  security JSONB NOT NULL DEFAULT '{}',
  api JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_leads_campaign_id ON leads(campaign_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_workspace_profiles_user_id ON workspace_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_app_settings_user_id ON app_settings(user_id);
